# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20170911_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='country_origin',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
